services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    platform: linux/amd64
    ports:
      - "2181:2181"
    networks:
      - ecommerce-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    command: "sh -c 'exec /usr/bin/start-kafka.sh'"
    depends_on:
      - zookeeper
    networks:
      - ecommerce-network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      BOOTSTRAP_SERVER: "kafka:9093"
    depends_on:
      - kafka
    networks:
      - ecommerce-network

  settlement-service:
    build:
      context: ./settlement-service
      dockerfile: Dockerfile
    environment:
      BOOTSTRAP_SERVER: "kafka:9093"
    depends_on:
      - kafka
    networks:
      - ecommerce-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-service
      - settlement-service
    networks:
      - ecommerce-network

volumes:
  cache:
    driver: local

networks:
  ecommerce-network:
    driver: bridge