server:
  port: 8081

kafka:
  bootstrap-server: ${BOOTSTRAP_SERVER:localhost:9092}
  consumer:
    group-id: settlement-service-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer