server:
  port: 8082

kafka:
  bootstrap-server: ${BOOTSTRAP_SERVER:localhost:9092}
  consumer:
    group-id: settlement-service-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

spring:
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement_service
    username: ecom
    password: ecom
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: password
