server:
  port: 8082

spring:
  liquibase:
    change-log: db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/settlement_service
    username: ecom
    password: ecom
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: password
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: settlement-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      order-created-topic: order-created